// Каталог работ NewComers Studio.
// featured-записи содержат badge/posterClass/description для карточки на project.html.
// Остальные записи используют общий шаблон карточки (см. project.html).
const LIBRARY = [
  // ---- Сериалы ----
  { slug: '1883', title: '1883', category: 'series', meta: 'Сезон 1' },
  { slug: '1899', title: '1899', category: 'series', meta: 'Сезон 1' },
  { slug: '1923', title: '1923', category: 'series', meta: 'Сезон 1' },
  { slug: 'a-knight-of-the-seven-kingdoms', title: 'A Knight of the Seven Kingdoms', category: 'series', meta: 'Сезон 1' },
  { slug: 'a-murder-at-the-end-of-the-world', title: 'A Murder at the End of the World', category: 'series', meta: 'Сезон 1' },
  { slug: 'a-thousand-blows', title: 'A Thousand Blows', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'agatha-all-along', title: 'Agatha All Along', category: 'series', meta: 'Сезон 1' },
  { slug: 'ahsoka', title: 'Ahsoka', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'andor', title: 'Andor', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'Disney+', posterClass: 'poster-andor',
    description: 'Приквел «Звёздных войн» о становлении будущего повстанца Кассиана Андора — задолго до событий «Изгоя-один».',
  },
  { slug: 'avatar-the-last-airbender', title: 'Avatar: The Last Airbender', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'beacon-23', title: 'Beacon 23', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'black-knight', title: 'Black Knight', category: 'series', meta: 'Сезон 1' },
  { slug: 'black-mirror', title: 'Black Mirror', category: 'series', meta: 'Сезон 6' },
  { slug: 'citadel', title: 'Citadel', category: 'series', meta: 'Сезон 1' },
  { slug: 'constellation', title: 'Constellation', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'daredevil-born-again', title: 'Daredevil: Born Again', category: 'series', meta: 'Сезон 1', featured: true,
    badge: 'Disney+', posterClass: 'poster-daredevil',
    description: 'Возвращение Мэтта Мёрдока — адвоката и супергероя Сорвиголовы — в новом сериале вселенной Marvel.',
  },
  { slug: 'dark-matter', title: 'Dark Matter', category: 'series', meta: 'Сезон 1' },
  { slug: 'devil-may-cry', title: 'Devil May Cry', category: 'series', meta: '2025 · Сезон 1' },
  { slug: 'disclaimer', title: 'Disclaimer', category: 'series', meta: 'Сезон 1' },
  { slug: 'dune-prophecy', title: 'Dune: Prophecy', category: 'series', meta: 'Сезон 1' },
  { slug: 'eric', title: 'Eric', category: 'series', meta: 'Сезон 1' },
  { slug: 'expats', title: 'Expats', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'fallout', title: 'Fallout', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'Prime Video', posterClass: 'poster-fallout',
    description: 'Экранизация культовой серии видеоигр о жизни после ядерной войны в ретрофутуристичной Америке.',
  },
  { slug: 'foundation', title: 'Foundation', category: 'series', meta: 'Сезон 3' },
  { slug: 'fubar', title: 'Fubar', category: 'series', meta: 'Сезон 1' },
  { slug: 'futurama', title: 'Futurama', category: 'series', meta: 'Сезон 11' },
  { slug: 'halo', title: 'Halo', category: 'series', meta: 'Сезоны 1–2' },
  {
    slug: 'harry-potter', title: 'Harry Potter', category: 'series', meta: 'Скоро', badge: 'HBO · Max',
    trailer: 'https://youtu.be/BzeCkvr9lDM?si=jwiA6F9cQVtkxXEs',
    description: 'Новая экранизация книг о Гарри Поттере в формате сериала от HBO.',
  },
  { slug: 'hijack', title: 'Hijack', category: 'series', meta: 'Сезон 2' },
  { slug: 'hotel-cocaine', title: 'Hotel Cocaine', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'house-of-the-dragon', title: 'House of the Dragon', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'HBO · Max', posterClass: 'poster-hotd', poster: 'assets/house-of-the-dragon.jpg',
    trailer: 'https://youtu.be/XF6zamFLO5w?si=l7bchQLytyB3cfO2',
    description: 'Приквел «Игры престолов» о войне за Железный трон между потомками рода Таргариенов — «Танце драконов».',
  },
  { slug: 'invincible', title: 'Invincible', category: 'series', meta: 'Сезоны 1–3' },
  { slug: 'krapopolis', title: 'Krapopolis', category: 'series', meta: 'Сезон 1' },
  { slug: 'landman', title: 'Landman', category: 'series', meta: 'Сезоны 1–2' },
  {
    slug: 'lanterns', title: 'Lanterns', category: 'series', meta: 'Скоро · 2026', badge: 'HBO · Max',
    trailer: 'https://youtu.be/8_cChUIXvBo?si=zMyHpkEVK_owTgGT',
    description: 'Сериал вселенной DC о Зелёных Фонарях — Хэле Джордане и Джоне Стюарте, охраняющих Землю от космических угроз.',
  },
  { slug: 'lawmen-bass-reeves', title: 'Lawmen: Bass Reeves', category: 'series', meta: 'Сезон 1' },
  { slug: 'like-a-dragon-yakuza', title: 'Like a Dragon: Yakuza', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'loki', title: 'Loki', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'Disney+', posterClass: 'poster-loki',
    description: 'Сериал вселенной Marvel о боге обмана Локи, который после событий «Мстителей» попадает в Управление Временными Изменениями.',
  },
  { slug: 'man-vs-baby', title: 'Man vs. Baby', category: 'series', meta: 'Сезон 1' },
  { slug: 'man-vs-bee', title: 'Man vs. Bee', category: 'series', meta: 'Сезон 1' },
  { slug: 'mobland', title: 'MobLand', category: 'series', meta: 'Сезон 1' },
  { slug: 'monarch-legacy-of-monsters', title: 'Monarch: Legacy of Monsters', category: 'series', meta: 'Сезон 1' },
  { slug: 'moon-knight', title: 'Moon Knight', category: 'series', meta: 'Сезон 1' },
  { slug: 'ms-marvel', title: 'Ms. Marvel', category: 'series', meta: 'Сезон 1' },
  { slug: 'obi-wan-kenobi', title: 'Obi-Wan Kenobi', category: 'series', meta: 'Сезон 1' },
  { slug: 'peacemaker', title: 'Peacemaker', category: 'series', meta: 'Сезон 1' },
  { slug: 'percy-jackson-and-the-olympians', title: 'Percy Jackson and the Olympians', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'presumed-innocent', title: 'Presumed Innocent', category: 'series', meta: 'Сезон 1' },
  { slug: 'rabbit-hole', title: 'Rabbit Hole', category: 'series', meta: 'Сезон 1' },
  { slug: 'robin-hood', title: 'Robin Hood', category: 'series', meta: '2025 · Сезон 1' },
  { slug: 'scott-pilgrim-takes-off', title: 'Scott Pilgrim Takes Off', category: 'series', meta: 'Сезон 1' },
  { slug: 'secret-invasion', title: 'Secret Invasion', category: 'series', meta: 'Сезон 1' },
  { slug: 'secret-level', title: 'Secret Level', category: 'series', meta: 'Сезон 1' },
  { slug: 'she-hulk-attorney-at-law', title: 'She-Hulk: Attorney at Law', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'shogun', title: 'Shogun', category: 'series', meta: 'Сезон 1', featured: true,
    badge: 'FX', posterClass: 'poster-shogun',
    description: 'Экранизация романа Джеймса Клавелла о европейце, оказавшемся при дворе средневековой Японии.',
  },
  {
    slug: 'silo', title: 'Silo', category: 'series', meta: 'Сезоны 2–3', poster: 'assets/silo.jpg',
    trailer: 'https://youtu.be/XNI0-lSg_rk?si=ykII85Af_hEY3YxE',
  },
  { slug: 'snowpiercer', title: 'Snowpiercer', category: 'series', meta: 'Сезон 4' },
  { slug: 'spartacus-house-of-ashur', title: 'Spartacus: House of Ashur', category: 'series', meta: 'Сезон 1' },
  { slug: 'star-trek-discovery', title: 'Star Trek: Discovery', category: 'series', meta: 'Сезон 5' },
  { slug: 'star-trek-starfleet-academy', title: 'Star Trek: Starfleet Academy', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'star-trek-strange-new-worlds', title: 'Star Trek: Strange New Worlds', category: 'series', meta: 'Сезон 4',
    badge: 'Paramount+', poster: 'assets/star-trek-strange-new-worlds.jpg',
    trailer: 'https://youtu.be/qv1ScNTi_TE?si=Vo-8Xg2WOStX16Rv',
  },
  { slug: 'star-wars-maul-shadow-lord', title: 'Star Wars: Maul – Shadow Lord', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'star-wars-skeleton-crew', title: 'Star Wars: Skeleton Crew', category: 'series', meta: 'Сезон 1', featured: true,
    badge: 'Disney+', posterClass: 'poster-skeleton',
    description: 'Приключенческий сериал «Звёздных войн» о группе детей, случайно улетевших со своей родной планеты.',
  },
  { slug: 'star-wars-tales-of-the-empire', title: 'Star Wars: Tales of the Empire', category: 'series', meta: 'Сезон 1' },
  { slug: 'star-wars-tales-of-the-jedi', title: 'Star Wars: Tales of the Jedi', category: 'series', meta: 'Сезон 1' },
  { slug: 'star-wars-tales-of-the-underworld', title: 'Star Wars: Tales of the Underworld', category: 'series', meta: 'Сезон 1' },
  { slug: 'star-wars-the-bad-batch', title: 'Star Wars: The Bad Batch', category: 'series', meta: 'Сезоны 1–3' },
  { slug: 'supernatural', title: 'Supernatural', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-acolyte', title: 'The Acolyte', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-consultant', title: 'The Consultant', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-continental', title: 'The Continental', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-day-of-the-jackal', title: 'The Day of the Jackal', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-falcon-and-the-winter-soldier', title: 'The Falcon and the Winter Soldier', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-gentlemen', title: 'The Gentlemen', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'the-last-of-us', title: 'The Last of Us', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'HBO · Max', posterClass: 'poster-tlou',
    description: 'Экранизация культовой видеоигры о выживших в мире, охваченном грибковой пандемией — путешествие Джоэла и Элли.',
  },
  { slug: 'the-lord-of-the-rings-the-rings-of-power', title: 'The Lord of the Rings: The Rings of Power', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'the-man-who-fell-to-earth', title: 'The Man Who Fell to Earth', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-morning-show', title: 'The Morning Show', category: 'series', meta: 'Сезон 3' },
  { slug: 'the-night-manager', title: 'The Night Manager', category: 'series', meta: 'Сезон 2' },
  { slug: 'the-old-man', title: 'The Old Man', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'the-penguin', title: 'The Penguin', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-peripheral', title: 'The Peripheral', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-sandman', title: 'The Sandman', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'the-walking-dead-daryl-dixon', title: 'The Walking Dead: Daryl Dixon', category: 'series', meta: 'Сезоны 1–2' },
  {
    slug: 'the-walking-dead-dead-city', title: 'The Walking Dead: Dead City', category: 'series', meta: 'Сезоны 1–2', featured: true,
    badge: 'AMC+', posterClass: 'poster-twd',
    description: 'Спин-офф «Ходячих мертвецов»: Мэгги и Неган отправляются в разрушенный, одичавший Манхэттен.',
  },
  { slug: 'the-walking-dead-the-ones-who-live', title: 'The Walking Dead: The Ones Who Live', category: 'series', meta: 'Сезон 1' },
  { slug: 'the-wheel-of-time', title: 'The Wheel of Time', category: 'series', meta: 'Сезоны 2–3' },
  { slug: 'the-winter-king', title: 'The Winter King', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'the-witcher', title: 'The Witcher', category: 'series', meta: 'Сезон 3', featured: true,
    badge: 'Netflix', posterClass: 'poster-witcher',
    description: 'История ведьмака Геральта из Ривии по мотивам книг Анджея Сапковского и игровой серии CD Projekt RED.',
  },
  { slug: 'the-pendragon-cycle-rise-of-the-merlin', title: 'The Pendragon Cycle: Rise of the Merlin', category: 'series', meta: 'Сезон 1' },
  { slug: 'tokyo-vice', title: 'Tokyo Vice', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'true-detective', title: 'True Detective', category: 'series', meta: 'Сезон 4' },
  { slug: 'true-lies', title: 'True Lies', category: 'series', meta: 'Сезон 1' },
  { slug: 'tulsa-king', title: 'Tulsa King', category: 'series', meta: 'Сезоны 1–2' },
  { slug: 'twisted-metal', title: 'Twisted Metal', category: 'series', meta: 'Сезон 1' },
  { slug: 'vikings-valhalla', title: 'Vikings: Valhalla', category: 'series', meta: 'Сезоны 2–3' },
  { slug: 'wandavision', title: 'WandaVision', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'wednesday', title: 'Wednesday', category: 'series', meta: 'Сезон 1', featured: true,
    badge: 'Netflix', posterClass: 'poster-wednesday',
    description: 'История Уэнсдэй Аддамс, которая поступает в академию Невермор и расследует местную тайну.',
  },
  { slug: 'white-house-plumbers', title: 'White House Plumbers', category: 'series', meta: 'Сезон 1' },
  { slug: 'willow', title: 'Willow', category: 'series', meta: 'Сезон 1' },
  {
    slug: 'x-men-97', title: 'X-Men ’97', category: 'series', meta: 'Сезон 1', featured: true,
    badge: 'Disney+', posterClass: 'poster-xmen',
    description: 'Прямое продолжение культового мультсериала 90-х годов про Людей Икс.',
  },

  // ---- Фильмы ----
  { slug: 'all-the-old-knives', title: 'All the Old Knives', category: 'movies', meta: '2022' },
  { slug: 'an-american-pickle', title: 'An American Pickle', category: 'movies', meta: '2020' },
  { slug: 'batman-soul-of-the-dragon', title: 'Batman: Soul of the Dragon', category: 'movies', meta: '2021' },
  { slug: 'batman-the-long-halloween-part-one', title: 'Batman: The Long Halloween, Part One', category: 'movies', meta: '2021' },
  { slug: 'batman-the-long-halloween-part-two', title: 'Batman: The Long Halloween, Part Two', category: 'movies', meta: '2021' },
  { slug: 'black-adam', title: 'Black Adam', category: 'movies', meta: '2022' },
  { slug: 'blame', title: 'Blame!', category: 'movies', meta: '2017' },
  { slug: 'bullet-train', title: 'Bullet Train', category: 'movies', meta: '2022' },
  { slug: 'child-of-kamiari-month', title: 'Child of Kamiari Month', category: 'movies', meta: '2021' },
  { slug: 'day-shift', title: 'Day Shift', category: 'movies', meta: '2022' },
  { slug: 'deep-water', title: 'Deep Water', category: 'movies', meta: '2022' },
  { slug: 'doctor-strange-in-the-multiverse-of-madness', title: 'Doctor Strange in the Multiverse of Madness', category: 'movies', meta: '2022' },
  { slug: 'dr-stone-ryuusui-special', title: 'Dr. Stone: Ryuusui (Special)', category: 'movies', meta: '2022' },
  { slug: 'dungeons-and-dragons-honor-among-thieves', title: 'Dungeons & Dragons: Honor Among Thieves', category: 'movies', meta: '2023' },
  { slug: 'enola-holmes', title: 'Enola Holmes', category: 'movies', meta: '2020' },
  { slug: 'enola-holmes-2', title: 'Enola Holmes 2', category: 'movies', meta: '2022' },
  { slug: 'extraction-2', title: 'Extraction 2', category: 'movies', meta: '2023' },
  { slug: 'fantastic-beasts-the-secrets-of-dumbledore', title: 'Fantastic Beasts: The Secrets of Dumbledore', category: 'movies', meta: '2022' },
  { slug: 'gods-crooked-lines', title: 'Gods Crooked Lines', category: 'movies', meta: '2022' },
  { slug: 'godzilla-gojira', title: 'Godzilla (Gojira)', category: 'movies', meta: '1954' },
  { slug: 'gold', title: 'Gold', category: 'movies', meta: '2022' },
  { slug: 'hustle', title: 'Hustle', category: 'movies', meta: '2022' },
  { slug: 'injustice', title: 'Injustice', category: 'movies', meta: '2021' },
  { slug: 'jurassic-world-dominion', title: 'Jurassic World: Dominion', category: 'movies', meta: '2022' },
  { slug: 'little-nemo-adventures-in-slumberland', title: 'Little Nemo: Adventures in Slumberland', category: 'movies', meta: '1989' },
  { slug: 'lupin-iii-the-first', title: 'Lupin III: The First', category: 'movies', meta: '2019' },
  { slug: 'morbius', title: 'Morbius', category: 'movies', meta: '2022' },
  { slug: 'mortal-kombat-legends-battle-of-the-realms', title: 'Mortal Kombat Legends: Battle of the Realms', category: 'movies', meta: '2021' },
  { slug: 'mortal-kombat-legends-scorpions-revenge', title: 'Mortal Kombat Legends: Scorpion’s Revenge', category: 'movies', meta: '2020' },
  { slug: 'mortal-kombat-legends-snow-blind', title: 'Mortal Kombat Legends: Snow Blind', category: 'movies', meta: '2022' },
  { slug: 'prey', title: 'Prey', category: 'movies', meta: '2022' },
  { slug: 'samaritan', title: 'Samaritan', category: 'movies', meta: '2022' },
  { slug: 'scoob', title: 'Scoob!', category: 'movies', meta: '2020' },
  { slug: 'spiderhead', title: 'Spiderhead', category: 'movies', meta: '2022' },
  { slug: 'superman-man-of-tomorrow', title: 'Superman: Man of Tomorrow', category: 'movies', meta: '2020' },
  { slug: 'the-aeronauts', title: 'The Aeronauts', category: 'movies', meta: '2019' },
  { slug: 'the-creator', title: 'The Creator', category: 'movies', meta: '2023' },
  { slug: 'the-devil-all-the-time', title: 'The Devil All the Time', category: 'movies', meta: '2020' },
  { slug: 'the-equalizer-3', title: 'The Equalizer 3', category: 'movies', meta: '2023' },
  { slug: 'the-family-plan', title: 'The Family Plan', category: 'movies', meta: '2023' },
  { slug: 'the-gray-man', title: 'The Gray Man', category: 'movies', meta: '2022' },
  { slug: 'the-killer', title: 'The Killer', category: 'movies', meta: '2023' },
  { slug: 'the-northman', title: 'The Northman', category: 'movies', meta: '2022' },
  { slug: 'the-out-laws', title: 'The Out-Laws', category: 'movies', meta: '2023' },
  { slug: 'the-tomorrow-war', title: 'The Tomorrow War', category: 'movies', meta: '2021' },
  { slug: 'the-unbearable-weight-of-massive-talent', title: 'The Unbearable Weight of Massive Talent', category: 'movies', meta: '2022' },
  { slug: 'we-bare-bears-the-movie', title: 'We Bare Bears: The Movie', category: 'movies', meta: '2020' },
  { slug: 'weathering-with-you', title: 'Weathering with You', category: 'movies', meta: '2019' },
  { slug: 'werewolf-by-night', title: 'Werewolf by Night', category: 'movies', meta: '2022' },

  // ---- Аниме ----
  { slug: 'bleach-thousand-year-blood-war', title: 'Bleach: Thousand-Year Blood War', category: 'anime', meta: 'Аниме-сериал', poster: 'assets/bleach-thousand-year-blood-war.jpg' },
  { slug: 'made-in-abyss', title: 'Made in Abyss', category: 'anime', meta: 'Сезоны 1–2' },
  { slug: 'shingeki-no-kyojin', title: 'Shingeki no Kyojin (Атака титанов)', category: 'anime', meta: 'Сезоны 2–4' },
];
